FROM ubuntu

RUN groupadd -r mygroup \
    && groupadd -r mygroup2 \
    && useradd -g mygroup myuser --groups mygroup2

USER myuser

# alguns comandos etc
# ...

USER root
COPY run-my-app.sh /usr/local/bin/run-my-app.sh
RUN chmod +x /usr/local/bin/run-my-app.sh

USER myuser

ENTRYPOINT ["/usr/local/bin/run-my-app.sh"]